module.exports = {
quotes: ["I love you the more in that I believe you had liked me for my own sake and for nothing else.",
"But man is not made for defeat. A man can be destroyed but not defeated.",
"When you reach the end of your rope, tie a knot in it and hang on.",
"There is nothing permanent except change.",
"You cannot shake hands with a clenched fist.",
"Let us sacrifice our today so that our children can have a better tomorrow.",
"The most difficult thing is the decision to act, the rest is merely tenacity. The fears are paper tigers",
"Do not mind anything that anyone tells you about anyone else. Judge everyone and everything for yourself.",
"Learning never exhausts the mind.",
"There is no charm equal to tenderness of heart.",
"All that we see or seem is but a dream within a dream.",
"Lord, make me an instrument of thy peace. Where there is hatred, let me sow love.",
"If you cannot do great things, do small things in a great way.",
"Permanence, perseverance and persistence in spite of all obstacles, discouragements, and impossibilitiesIndependence is happiness.",
"The supreme art of war is to subdue the enemy without fighting.",
"Keep your face always toward the sunshine - and shadows will fall behind you.",
"Happiness can exist only in acceptance.",
"Love has no age, no limit; and no death.",
"You can't blame gravity for falling in love." ,
"There is only one corner of the universe you can be certain of improving, and that's your own self.",
"Honesty is the first chapter in the book of wisdom.",
"The journey of a thousand miles begins with one step.",
"Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
"Do the difficult things while they are easy and do the great things while they are small. A journey of a thousand miles must begin with a single step.",
"The journey of a thousand miles begins with one step.",
"A good traveler has no fixed plans, and is not intent on arriving.",
"Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.",
"Nothing is softer or more flexible than water, yet nothing can resist it.",
"Life is a series of natural and spontaneous changes. Don't resist them - that only creates sorrow. Let reality be reality. Let things flow naturally forward in whatever way they like.",
"Silence is a source of great strength.",
"He who knows, does not speak. He who speaks, does not" ,
"Music in the soul can be heard by the universe.",
"When the best leader's work is done the people say, 'We did it ourselves.'" ,
"I have just three things to teach: simplicity, patience, compassion. These three are your greatest treasures." ,
"Knowing others is wisdom, knowing yourself is Enlightenment." ,
"Life and death are one thread, the same line viewed from different sides." ,
"The key to growth is the introduction of higher dimensions of consciousness into our awareness." ,
"If you do not change direction, you may end up where you are heading." ,
"A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves." ,
"To the mind that is still, the whole universe surrenders." ,
"Governing a great nation is like cooking a small fish - too much handling will spoil it." ,
"He who controls others may be powerful, but he who has mastered himself is mightier still." ,
"When I let go of what I am, I become what I might be." ,
"From caring comes courage." ,
"Manifest plainness, embrace simplicity, reduce selfishness, have few desires." ,
"Be content with what you have; rejoice in the way things are. When you realize there is nothing lacking, the whole world belongs to you." ,
"If you would take, you must first give, this is the beginning of intelligence." ,
"Promise me you'll always remember: You're braver than you believe, and stronger than you seem, and smarter than you think." ,
"Weeds are flowers too, once you get to know them." ,
"Organizing is what you do before you do something, so that when you do it, it is not all mixed up." ,
"You can't stay in your corner of the forest waiting for others to come to you. You have to go to them sometimes." ,
"It is more fun to talk with someone who doesn't use long, difficult words but rather short, easy words, like 'What about lunch?'" ,
"If you live to be a hundred, I want to live to be a hundred minus one day so I never have to live without you." ,
"To the uneducated, an A is just three sticks." ,
"Don't underestimate the value of doing nothing, of just going along, listening to all the thing you can't hear, and not bothering." ,
"A clever conjurer is welcome anywhere, and those of us whose powers of entertainment are limited to the setting of booby-traps or the arranging of apple-pie beds must view with envy the much greater tribute of laughter and applause which is the lot of the prestidigitator with some natural gift for legerdemain." ,
"Did you ever stop to think, and forget to start again?" ,
"If one is to be called a liar, one may as well make an effort to deserve the name." ,
"Never forget me, because if I thought you would, I'd never leave." ,
"The third-rate mind is only happy when it is thinking with the majority. The second-rate mind is only happy when it is thinking with the minority. The first-rate mind is only happy when it is thinking." ,
"A writer wants something more than money for his work: he wants permanence." ,
"Some people care too much. I think it's called love." ,
"You will be better advised to watch what we do instead of what we say." ,
"Golf is so popular simply because it is the best game in the world at which to be bad." ,
"What I say is that, if a fellow really likes potatoes, he must be a pretty decent sort of fellow." ,
"One of the advantages of being disorderly is that one is constantly making exciting discoveries." ,
"Is 'The Wind in the Willows' a children's book? Is 'Alice in Wonderland?' Is 'Treasure Island?' These are masterpieces which we read with pleasure as children, but with how much more pleasure when we are grown-up.",
"I gave up writing children's books. I wanted to escape from them as I had once wanted to escape from 'Punch': as I have always wanted to escape. In vain." ,
"My spelling is Wobbly. It's good spelling but it Wobbles, and the letters get in the wrong places." ,
"Bores can be divided into two classes; those who have their own particular subject, and those who do not need a subject." ,
"War is something of man's own fostering, and if all mankind renounces it, then it is no longer there." ,
"Tiggers don't like honey." ,
"All that is gold does not glitter, not all those who wander are lost; the old that is strong does not wither, deep roots are not reached by the frost." ,
"Still round the corner there may wait, A new road or a secret gate." ,
"If more of us valued food and cheer and song above hoarded gold, it would be a merrier world." ,
"Not all those who wander are lost." ,
"The wide world is all about you: you can fence yourselves in, but you cannot forever fence it out." ,
"All we have to decide is what to do with the time that is given us." ,
"Faithless is he that says farewell when the road darkens." ,
"It's the job that's never started as takes longest to finish." ,
"Courage is found in unlikely places." ,
"Many that live deserve death. And some that die deserve life. Can you give it to them? Then do not be too eager to deal out death in judgement. For even the very wise cannot see all ends." ,
"So comes snow after fire, and even dragons have their ending!" ,
"Short cuts make long delays." ,
"I don't know half of you half as well as I should like; and I like less than half of you half as well as you deserve." ,
"A box without hinges, key, or lid, yet golden treasure inside is hid." ,
"Do not meddle in the affairs of Wizards, for they are subtle and quick to anger." ,
"It does not do to leave a live dragon out of your calculations, if you live near him." ,
"I don't like allegories." ,
"Go not to the Elves for counsel, for they will say both no and yes." ,
"I dislike Allegory - the conscious and intentional allegory - yet any attempt to explain the purport of myth or fairytale must use allegorical language." ,
"You have been chosen, and you must therefore use such strength and heart and wits as you have." ,
"39;I wish life was not so short,' he thought. 'Languages take such a time, and so do all the things one wants to know about.'" ,
"Treat a work of art like a prince. Let it speak to you first." ,
"Talent hits a target no one else can hit; Genius hits a target no one else can see." ,
"Just remember, once you're over the hill you begin to pick up speed." ,
"Each day is a little life: every waking and rising a little birth, every fresh morning a little youth, every going to rest and sleep a little death." ,
"A man can be himself only so long as he is alone, and if he does not love solitude, he will not love freedom, for it is only when he is alone that he is really free." ,
"All truth passes through three stages. First, it is ridiculed. Second, it is violently opposed. Third, it is accepted as being self-evident." ,
"The doctor sees all the weakness of mankind; the lawyer all the wickedness, the theologian all the stupidity." ,
"The two enemies of human happiness are pain and boredom." ,
"Compassion is the basis of morality." ,
"Every parting gives a foretaste of death, every reunion a hint of the resurrection." ,
"Great men are like eagles, and build their nest on some lofty solitude." ,
"I've never known any trouble than an hour's reading didn't assuage." ,
"Politeness is to human nature what warmth is to wax." ,
"With people of limited ability modesty is merely honesty. But with those who possess great talent it is hypocrisy." ,
"To live alone is the fate of all great souls." ,
"Wealth is like sea-water; the more we drink, the thirstier we become; and the same is true of fame." ,
"Change alone is eternal, perpetual, immortal." ,
"Great minds are related to the brief span of time during which they live as great buildings are to a little square in which they stand: you cannot see them in all their magnitude because you are standing too close to them." ,
"Nature shows that with the growth of intelligence comes increased capacity for pain, and it is only with the highest degree of intelligence that suffering reaches its supreme point." ,
"Religion is the masterpiece of the art of animal training, for it trains people as to how they shall think." ,
"There is no doubt that life is given us, not to be enjoyed, but to be overcome; to be got over." ,
"A man's face as a rule says more, and more interesting things, than his mouth, for it is a compendium of everything his mouth will ever say, in that it is the monogram of all this man's thoughts and aspirations." ,
"The greatest of follies is to sacrifice health for any other kind of happiness." ,
"A man can do what he wants, but not want what he wants." ,
"To give real service you must add something which cannot be bought or measured with money, and that is sincerity and integrity." ,
"I love deadlines. I like the whooshing sound they make as they fly by." ,
"The knack of flying is learning how to throw yourself at the ground and miss." ,
"A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools." ,
"Time is an illusion. Lunchtime doubly so." ,
"There is a theory which states that if ever anyone discovers exactly what the Universe is for and why it is here, it will instantly disappear and be replaced by something even more bizarre and inexplicable. There is another theory which states that this has already happened." ,
"Every country is like a particular type of person. America is like a belligerent, adolescent boy; Canada is like an intelligent, 35-year-old woman. Australia is like Jack Nicholson. It comes right up to you and laughs very hard in your face in a highly threatening and engaging manner." ,
"One of the most important things you learn from the Internet is that there is no 'them' out there. It's just an awful lot of 'us.'" ,
"I think fish is nice, but then I think that rain is wet, so who am I to judge?" ,
"He was a dreamer, a thinker, a speculative philosopher... or, as his wife would have it, an idiot." ,
"This must be Thursday. I never could get the hang of Thursdays." ,
"I briefly did therapy, but after a while, I realised it is just like a farmer complaining about the weather. You can't fix the weather - you just have to get on with it." ,
"In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move." ,
"I seldom end up where I wanted to go, but almost always end up where I need to be." ,
"Human beings, who are almost unique in having the ability to learn from the experience of others, are also remarkable for their apparent disinclination to do so." ,
"Any man who can hitch the length and breadth of the galaxy, rough it, slum it, struggle against terrible odds, win through, and still knows where his towel is is clearly a man to be reckoned with." ,
"I may not have gone where I intended to go, but I think I have ended up where I intended to be." ,
"What the computer in virtual reality enables us to do is to recalibrate ourselves so that we can start seeing those pieces of information that are invisible to us but have become important for us to understand." ,
"In order to fly, all one must do is simply miss the ground." ,
"If somebody thinks they're a hedgehog, presumably you just give 'em a mirror and a few pictures of hedgehogs and tell them to sort it out for themselves." ,
"It is a mistake to think you can solve any major problems just with potatoes." ,
"I find the whole business of religion profoundly interesting. But it does mystify me that otherwise intelligent people take it seriously." ,
"My absolute favourite piece of information is the fact that young sloths are so inept that they frequently grab their own arms and legs instead of tree limbs, and fall out of trees." ,
"Anyone who is capable of getting themselves made President should on no account be allowed to do the job." ,
"If it looks like a duck, and quacks like a duck, we have at least to consider the possibility that we have a small aquatic bird of the family anatidae on our hands." ,
"The major difference between a thing that might go wrong and a thing that cannot possibly go wrong is that when a thing that cannot possibly go wrong goes wrong it usually turns out to be impossible to get at and repair." ,
"In ancient times cats were worshipped as gods; they have not forgotten this." ,
"The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it." ,
"The pen is mightier than the sword if the sword is very short, and the pen is very sharp." ,
"They say a little knowledge is a dangerous thing, but it's not one half so bad as a lot of ignorance." ,
"Light thinks it travels faster than anything but it is wrong. No matter how fast light travels, it finds the darkness has always got there first, and is waiting for it." ,
"It's useful to go out of this world and see it from the perspective of another one." ,
"Most gods throw dice, but Fate plays chess, and you don't find out til too late that he's been playing with two queens all along." ,
"Sometimes it is better to light a flamethrower than curse the darkness." ,
"He was the sort of person who stood on mountaintops during thunderstorms in wet copper armour shouting 'All the Gods are bastards.'" ,
"Evolution was far more thrilling to me than the biblical account. Who would not rather be a rising ape than a falling angel? To my juvenile eyes, Darwin was proved true every day. It doesn't take much to make us flip back into monkeys again." ,
"We have been so successful in the past century at the art of living longer and staying alive that we have forgotten how to die. Too often we learn the hard way. As soon as the baby boomers pass pensionable age, their lesson will be harsher still." ,
"Never trust any complicated cocktail that remains perfectly clear until the last ingredient goes in, and then immediately clouds." ,
"Only in our dreams are we free. The rest of the time we need wages." ,
"Go on, prove me wrong. Destroy the fabric of the universe. See if I care." ,
"I'll be more enthusiastic about encouraging thinking outside the box when there's evidence of any thinking going on inside it." ,
"My advice is this. For Christ's sake, don't write a book that is suitable for a kid of 12 years old, because the kids who read who are 12 years old are reading books for adults. I read all of the James Bond books when I was about 11, which was approximately the right time to read James Bond books." ,
"This isn't life in the fast lane, it's life in the oncoming traffic." ,
"My experience in Amsterdam is that cyclists ride where the hell they like and aim in a state of rage at all pedestrians while ringing their bell loudly, the concept of avoiding people being foreign to them." ,
"Previous generations understood about death, and undoubtedly would have seen a reasonable amount of death. Once you get into the Victorian era, you might well have seen the funerals of many of your siblings before you were very old." ,
"It is often said that before you die your life passes before your eyes. It is in fact true. It's called living." ,
"Build a man a fire, and he'll be warm for a day. Set a man on fire, and he'll be warm for the rest of his life." ,
"Fantasy is an exercise bicycle for the mind. It might not take you anywhere, but it tones up the muscles that can. Of course, I could be wrong." ,
"The intelligence of the creature known as a crowd, is the square root of the number of people in it." ,
"In the beginning there was nothing, which exploded." ,
"It's not worth doing something unless you were doing something that someone, somewere, would much rather you weren't doing." ,
"I think when people mean that Discworld books have become darker they really mean the series is growing up. In 'The Colour of Magic' most of the city is set alight. It's a joke, in much the same way that the Earth is destroyed almost at the start of Douglas Adams's 'The Hitchhikers Guide to the Galaxy.''"]
}
